# Generated by Django 5.0.7 on 2024-08-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_num', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=75, verbose_name='Email')),
                ('text_inform', models.CharField(max_length=350, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
