# Generated by Django 5.0.7 on 2024-08-13 16:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_callback_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
